name: 'Get Git Log Action'
description: 'Get git log from specify git tag to the present'
author: 'JantHsueh'
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  tag:
    description: 'Specify git tag'
    required: false
outputs:
  log:
    description: 'git logs'
  tag
    description: 'Triggered tag'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag }}
